In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("Output/output_GoG2.txt")
df.describe()

             p            k           b/c             n       result
count  1000.00  1000.000000  1.000000e+03   1000.000000  1000.000000
mean      0.02     3.931200  2.100000e+00    717.876000     0.236000
std       0.00     0.195272  8.886228e-16   1650.248507     2.928289
min       0.02     3.200000  2.100000e+00      0.000000     0.000000
25%       0.02     3.800000  2.100000e+00     34.000000     0.000000
50%       0.02     3.920000  2.100000e+00    127.000000     0.000000
75%       0.02     4.060000  2.100000e+00    502.500000     0.000000
max       0.02     4.720000  2.100000e+00  10000.000000    64.000000

In [6]:
df = pd.read_csv("Output/output_GoG3.txt")
df.describe()

             p            k           b/c             n       result
count  1000.00  1000.000000  1.000000e+03   1000.000000  1000.000000
mean      0.02     3.932760  2.200000e+00    661.187000     0.072000
std       0.00     0.193637  4.443114e-16   1497.095237     1.089956
min       0.02     3.360000  2.200000e+00      0.000000     0.000000
25%       0.02     3.800000  2.200000e+00     36.000000     0.000000
50%       0.02     3.940000  2.200000e+00    116.000000     0.000000
75%       0.02     4.060000  2.200000e+00    466.250000     0.000000
max       0.02     4.560000  2.200000e+00  10000.000000    22.000000

In [7]:
df = pd.read_csv("Output/output_GoG4.txt")
df.describe()

             p           k     b/c             n       result
count  1000.00  1000.00000  1000.0   1000.000000  1000.000000
mean      0.02     3.93728     2.3    612.865000     0.158000
std       0.00     0.19493     0.0   1405.802692     2.637421
min       0.02     3.30000     2.3      0.000000     0.000000
25%       0.02     3.80000     2.3     34.000000     0.000000
50%       0.02     3.94000     2.3    109.500000     0.000000
75%       0.02     4.06000     2.3    454.250000     0.000000
max       0.02     4.54000     2.3  10000.000000    68.000000

In [8]:
df = pd.read_csv("Output/output_GoG5.txt")
df.describe()

              p             k      b/c             n        result
count  10000.00  10000.000000  10000.0  10000.000000  10000.000000
mean       0.02      3.918882      3.0    673.206500      0.246100
std        0.00      0.192445      0.0   1607.008951      3.041128
min        0.02      3.240000      3.0      0.000000      0.000000
25%        0.02      3.780000      3.0     34.000000      0.000000
50%        0.02      3.920000      3.0    113.000000      0.000000
75%        0.02      4.040000      3.0    445.000000      0.000000
max        0.02      4.660000      3.0  10000.000000     88.000000

In [9]:
df = pd.read_csv("Output/output_GoG6.txt")
df.describe()

              p             k      b/c             n       result
count  10000.00  10000.000000  10000.0  10000.000000  10000.00000
mean       0.02      3.919464      5.0    632.068200      0.18390
std        0.00      0.196571      0.0   1516.684903      2.80679
min        0.02      3.120000      5.0      0.000000      0.00000
25%        0.02      3.780000      5.0     32.000000      0.00000
50%        0.02      3.920000      5.0    110.000000      0.00000
75%        0.02      4.040000      5.0    436.500000      0.00000
max        0.02      4.720000      5.0  10000.000000     98.00000

In [30]:
df = pd.read_csv("Output/output_GoG_4_6.txt")
df.describe()

             p            k           b/c             n       result
count  1000.00  1000.000000  1.000000e+03   1000.000000  1000.000000
mean      0.02     3.926760  4.200000e+00    800.102000     3.900000
std       0.00     0.198448  1.777246e-15   2449.310661    19.369181
min       0.02     3.340000  4.200000e+00      1.000000     0.000000
25%       0.02     3.780000  4.200000e+00     38.000000     0.000000
50%       0.02     3.920000  4.200000e+00    114.000000     0.000000
75%       0.02     4.060000  4.200000e+00    370.250000     0.000000
max       0.02     4.660000  4.200000e+00  25140.000000   100.000000